name: moritz
favicon: null
layout_spectrum: 0.026261143619194627
typography_spectrum: 0.9643903046380728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23244371614418924
  lightness: 0.5926497217733413
  saturation: 0.30442403070628643
  rhythmicContrast: 0.7011107983998954
purpose: []
