purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6875
  brandStrength: 0.5
  lightness: 0.625
  brandColors:
    - '#ABA99D'
    - '#CACCBF'
    - '#4B443E'
    - '#736C66'
    - '#EAEBE3'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: moritz
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.25439
layout_spectrum: 0.19627
